Entity/BusinessUnitInterface.php
<?php

namespace Oro\Bundle\OrganizationBundle\Entity;

interface BusinessUnitInterface
{
    /**
     * @return int
     */
    public function getId();

    /**
     * @return string
     */
    public function getName();
}

Form/Type/OwnershipType.php
<?php

namespace Oro\Bundle\OrganizationBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use Symfony\Component\Translation\TranslatorInterface;

class OwnershipType extends AbstractType
{
    const NAME = 'oro_type_choice_ownership_type';

    const OWNER_TYPE_NONE = 'NONE';
    const OWNER_TYPE_USER = 'USER';
    const OWNER_TYPE_BUSINESS_UNIT = 'BUSINESS_UNIT';
    const OWNER_TYPE_ORGANIZATION = 'ORGANIZATION';

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(
            array(
                'choices' => $this->getOwnershipsArray()
            )
        );
    }

    public function getOwnershipsArray()
    {
        return  array(
            self::OWNER_TYPE_NONE => 'None',
            self::OWNER_TYPE_USER => 'User',
            self::OWNER_TYPE_BUSINESS_UNIT => 'Business Unit',
            self::OWNER_TYPE_ORGANIZATION => 'Organization',
        );
    }

    public function getParent()
    {
        return 'choice';
    }

    public function getName()
    {
        return $this->getBlockPrefix();
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return self::NAME;
    }
}

Resources/views/owner.html.twig
{% if form.owner is defined %}
    {% if form.owner.vars.label == 'oro.organization.businessunit.parent.label' %}
        {{ form_row(form.owner) }}
    {% else %}
        {{ form_row(form.owner, {'label': label is not same as(false) ? label : ''}) }}
    {% endif %}
{% endif %}

Resources/views/viewOwnerInfo.html.twig
{% import 'OroUserBundle::macros.html.twig' as U %}
{% if  resource_granted('VIEW', entity, oro_get_owner_field_name(entity)) %}
    {% if bracket_parts is not defined %}
        {% set bracket_parts = [] %}
    {% endif %}
    {% set ownerType = oro_get_owner_type(entity) %}
    {% if ownerType == 'USER' %}
        {% set userOwner = oro_get_entity_owner(entity) %}
        {% if userOwner %}
            {% set businessUnitName = U.user_business_unit_name(userOwner, false) %}
            {% if businessUnitName is not empty %}
                {% set bracket_parts = [businessUnitName]|merge(bracket_parts) %}
            {% endif %}
        {% endif %}
    {% elseif ownerType == 'ORGANIZATION' %}
        {% if organizationInfo is not defined %}
            {% set organizationOwner = oro_get_entity_owner(entity) %}
            {% if organizationOwner is not null %}
                {% set organizationInfo =  'oro.ui.owner'|trans ~ ': ' ~ organizationOwner.name %}
            {% else %}
                {% set organizationInfo = '' %}
            {% endif %}
        {% endif %}
        {{ organizationInfo|raw }}
    {% endif %}
    {% if bracket_parts is not empty %}
        ({{ bracket_parts|join(', ')|raw }})
    {% endif %}
{% endif %}